<?php

use Illuminate\Support\MessageBag;

class ConjugatedProduct extends Product {

    /**
     * Attributes that will be generated by FactoryMuff
     */
    public static $factory = array(
        'name' => 'text',
        'category' => 'factory|Category',
        'shortDesc' => 'text',
        'description' => 'text',
        'active' => true,
    );

    /**
     * The attached products that compose a conjugated
     */
    public function products()
    {
        return $this->referencesMany('Product','conjugated');
    }

    public function save( $force = false )
    {
        if($this->_id == null)
        {
            $this->_id = 'CJ'.
                substr(microtime(),-8).
                substr(rand(),-3);
        }

        if(parent::save())
        {
            return true;
        }
        else
        {
            unset($this->_id);
            return false;
        }
    }

    /**
     * Overwrites the isValid method in order to check if
     * the conjugated combination is unique and if all the
     * _ids specified exists.
     *
     */
    public function isValid()
    {
        if( parent::isValid() )
        {
            // Check if there is another conjugated combination that is
            // equals to the current.
            if(
                ConjugatedProduct::where(
                    ['conjugated'=>$this->conjugated, '_id'=>['$ne'=>$this->_id ] ]
                )->count()
            )
            {
                $this->errors = new MessageBag(
                    ['Combinação Duplicada', "Já existe um produto conjugado com esta combinação."]
                );
                return false;
            }

            // Check if all the lms are valid.
            if(
                Product::where(
                    ['lm'=>['$in'=>$this->conjugated ] ]
                )->count() != count($this->conjugated)
            )
            {
                $this->errors = new MessageBag(
                    ['LM Inválido', "Um ou mais LMs são invalidos. Verifique se não existem LMs duplicados ou incorretos no conjugado."]
                );
                return false;
            }

            return true;
        }

        return false;     
    }
}
