<?php

use Illuminate\Support\MessageBag;

class ConjugatedProduct extends Product {

    /**
     * Attributes that will be generated by FactoryMuff
     */
    public static $factory = array(
        'name' => 'text',
        'category' => 'factory|Category',
        'shortDesc' => 'text',
        'description' => 'text',
        'active' => true,
    );

    /**
     * The attached products that compose a conjugated
     */
    public function products()
    {
        return $this->referencesMany('Product','conjugated');
    }

    public function save( $force = false )
    {
        if($this->_id == null)
        {
            $this->_id = 'CJ'.
                substr(microtime(),-8).
                substr(rand(),-3);
        }

        if(parent::save( $force ))
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    /**
     * Overwrites the setAttribute method in order to
     * explode a string into array before setting the
     * conjugated attribute
     *
     * @param  string  $key
     * @param  mixed   $value
     * @return void
     */
    public function setAttribute($key, $value)
    {
        if($key == 'conjugated')
        {
            if(is_string($value))
            {
                $value = array_map('intval',explode(",",strtolower($value)));
            }
        }

        return parent::setAttribute($key, $value);
    }

    /**
     * Overwrites the isValid method in order to check if
     * the conjugated combination is unique and if all the
     * _ids specified exists.
     *
     */
    public function isValid()
    {
        if( parent::isValid() )
        {
            // Check if the conjugated product have at least two products
            if( count((array)$this->conjugated) < 2 )
            {
                $this->errors = new MessageBag(
                    ['Conjugação mínima', "Um produto conjugado deve possuir pelo menos 2 LMs de produto."]
                );
                return false;
            }

            // Check if there is another conjugated combination that is
            // equals to the current.
            if(
                ConjugatedProduct::where(
                    ['conjugated'=>$this->conjugated, '_id'=>['$ne'=>$this->_id ] ]
                )->count()
            )
            {
                $this->errors = new MessageBag(
                    ['Combinação Duplicada', "Já existe um produto conjugado com esta combinação."]
                );
                return false;
            }

            // Check if all the lms are valid.
            if(
                Product::where(
                    ['_id'=>['$in'=>$this->conjugated ] ]
                )->count() != count($this->conjugated)
            )
            {
                $this->errors = new MessageBag(
                    ['LM Inválido', "Um ou mais LMs são invalidos. Verifique se não existem LMs duplicados ou incorretos no conjugado."]
                );
                return false;
            }

            return true;
        }

        return false;     
    }
}
