<?php

use Illuminate\Support\MessageBag;

class ConjugatedProduct extends BaseModel {

    /**
     * Attributes that will be generated by FactoryMuff
     */
    public static $factory = array(
        'name' => 'text',
        'category' => 'factory|Category',
        'shortDesc' => 'text',
        'description' => 'text',
        'active' => true,
    );

    public function save( $force = false )
    {
        if($this->_id == null)
        {
            $this->_id = 'CJ'.
                substr(microtime(),-8).
                substr(rand(),-3);
        }

        if(parent::save())
        {
            return true;
        }
        else
        {
            unset($this->_id);
            return false;
        }
    }

    /**
     * Overwrites the isValid method in order to check if
     * the conjugated combination is unique and if all the
     * _ids specified exists.
     *
     */
    public function isValid()
    {
        if( parent::isValid() )
        {
            if(
                ConjugatedProduct::where(
                    ['conjugated'=>$this->conjugated, '_id'=>['$ne'=>$this->_id ] ]
                )->count()
            )
            {
                return false;
            }

            if(
                Product::where(
                    ['lm'=>['$in'=>$this->conjugated ] ]
                )->count() != count($this->conjugated)
            )
            {
                return false;
            }

            return true;
        }

        return false;     
    }

}
